### ISSUE TITLE
Transformation function over joined sources?

### ISSUE THREAD

**Issue by dachafra** [kg-construct/rml-fno-spec#1]
Having two sources (A and B) that can be joined by a field, would be possible to apply functions on some B fields and using them in any part of the TriplesMap from A?

Let me put an example.
Table A:
| AC1 | AC2 |
|------|------|
| a    | a1   |
| b    | b1   |

Table B
| BC1 | BC2       |
|-----|-----------|
| a1  | "hello a" |
| b1  | "hello b" |

Output (applying uppercase to BC2)
```
<http://example.org/a> ex:predicate "HELLO A"^^xsd:string
<http://example.org/b> ex:predicate "HELLO B"^^xsd:string
```
I don't know if it is currently possible declaring the join-condition in the mapping rules or should we have to create an ad-hoc implemented function?

**Comment by bjdmeest** [comment]
I have the feeling these are two issues:
- joining _values_ of a second source as objects of a first source (which I don't think is currently feasible in RML?)
- executing a function over a join result

Right now
- it is possible to join values across data sources, but without join conditions (see eg https://github.com/RMLio/rml-fno-test-cases/blob/master/RMLFNOTC0009-CSV/mapping.ttl, also brought up by @pmaria at https://kg-construct.slack.com/archives/C01QFSW77QF/p1615717859003600)
- it is possible to nest functions (see eg https://github.com/RMLio/rml-fno-test-cases/blob/master/RMLFNOTC0018-CSV/mapping.ttl)

For what you want, I think we need both (i) a function with a nested condition (in RML+FnO), and (ii) the ability to describe a join condition that does not return the subject of a triples map, but something else, maybe it returns the right iteration from a different logical source, so that we could use a reference formulation to take any data field from that iteration (in RML)

What I propose to do:

- [ ] I create new issue to describe the current "it is possible to join values across data sources, but without join conditions" in this spec
- [ ] I create new issue to describe the current "it is possible to nest functions" in this spec
- [ ] I create new issue to specify feature request "executing a function over a join result" here (still to be discussed, bc I think that depends on how we handle the next bullet point)
- [ ] I create new mapping challenge "joining _values_ of a second source as objects of a first source" in the mapping challenges repo

WDYT?

**Comment by pmaria** [comment]
Isn't  "joining values of a second source as objects of a first source" the same as the mapping challeng "join on literals"? At least, that's how I interpreted the latter.

I agree with the above. I also feel that it would be good to solve that issue in RML first, before deciding on how iterations in "function triples maps" should work. It might save us from making things overly complex.

**Comment by bjdmeest** [comment]
> Isn't "joining values of a second source as objects of a first source" the same as the mapping challeng "join on literals"? At least, that's how I interpreted the latter.

You're totally right, forgot that was already in there 😅

**Comment by dachafra** [comment]
> Isn't "joining values of a second source as objects of a first source" the same as the mapping challenge "join on literals"? At least, that's how I interpreted the latter.
 
Totally agree with this too!

**Comment by pmaria** [comment]
Saved you hours of work there @bjdmeest 😂

**Comment by dachafra** [comment]
@bjdmeest as this issue has been split into three new issues, where we are actually discussing all, shall we close this?

**Comment by bjdmeest** [comment]
awesome, yes!
